---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Athos Rocha, Louis Weil, Ethan Wood, Lucas Smith, Jake Cullen and Aniruddh Iyer"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")

# Member 4 (pair 2) write code to load File 2 data here:
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")


# Member 6 (pair 3) write code to load File 3 data here:
data3 <- read_tsv("data/UN_country_population.tsv")


# Member 1 (pair 1) write code to load File 4 data here:
data4 <- read_excel("data/UN_country_region.xlsx")


```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':
plastic_data_all <- data1



# Member 4 (pair 2) write code to join your data to 'plastic_data_all':
plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")



# Member 6 (pair 3) write code to join your data to 'plastic_data_all':
plastic_data_all <- data3 |> 
  select(-name) |> 
  right_join(plastic_data_all, by = "code")



# Member 1 (pair 1) write code to join your data to 'plastic_data_all':
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'
plastic_data_all %>% head(n = 10)


```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}

plastic_data_all |> 
  group_by(region) |> 
  count(region)

#Africa has the greatest number of coastal territories/regions
```



### Ex 2.

```{r Ex2, message = FALSE}

plastic_data_all |> 
  mutate(total_mismanage_plastic = mismanaged_plastic * population)

plastic_data_all |> 
  mutate(
    total_mismanaged_plastic = mismanaged_plastic * population) |> 
  group_by(region) |> 
  summarise(mean_mismanaged_waste = mean(total_mismanaged_plastic)) |> 
  arrange(desc(mean_mismanaged_waste))

# Asia has the highest mean total mismanaged plastic waste while Oceania has the least.

```


### Ex 3.

```{r Ex3, message = FALSE}

plastic_data_all |> 
  mutate(
   pct_mismanaged_plastic_ocean = 
   (mismanaged_plastic_ocean/mismanaged_plastic) * 100
  ) |> 
  drop_na() |> 
  group_by(region) |> 
  summarise(med_pct_mismanaged_plastic_ocean 
            = median(pct_mismanaged_plastic_ocean)) |> 
  arrange(desc(med_pct_mismanaged_plastic_ocean))



# Africa's value for median pct_mismanaged_plastic_ocean is initially NA as it has no values for the ocean and plastic waste when the code is "SOM" which is in Somalia. Essentially the code is trying to find the median of a percentage that is undefined so it spits out NA.

# The command drop_na() has to be added to remove any NA's.

# Africa has the lowest median out of all the regions listed.

```


### Ex 4.

```{r Ex4, message = FALSE}
plastic_data_all |> 
  rename(pop = population, mis_plastic = mismanaged_plastic,
         mis_ocean_plastic = mismanaged_plastic_ocean) |> 
  mutate(
    region = str_replace_all(region, "Latin America and The Caribbean", "LAC"),
    prop = (mis_ocean_plastic/mis_plastic)*100
  ) |> 
  drop_na() |> 
  group_by(region) |> 
  summarise(
    pop = sum(pop),
    mean_prop = mean(prop)
  ) |> 
  arrange(desc(pop))

# From this data we see that regions that are more coastal (e.g. LAC, Oceania) have a higher proportion of ocean waste which is what we would expect. Asia still has a high proportion which could just be due to the large population it has.


```
